import {defineConfig} from 'tsup'
import packageJson from './package.json' assert { type : 'json' }

export default defineConfig({
    entry:['src/marked.ts'],
    format:['esm'],
    dts:true,
    splitting:false,
    sourcemap:false,
    clean:true,
    minify:false,
    banner:{js:`/**
    * marked v${ packageJson.version} - a markdown parser
    * Copyright (c) 2011-${new Date().getFullYear()}, Christopher Jeffrey. (MIT Licensed)
    * https://github.com/markedjs/marked
    */
   
   /**
    * DO NOT EDIT THIS FILE
    * The code in this file is generated from files in ./src/
    */`},
    outDir:"lib"
})
